version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/db
      AWS_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY: minioadmin
      AWS_SECRET_KEY: minioadmin
      S3_BUCKET: uploads
      JWT_SECRET: changeme
      REDIS_URL: redis://redis:6379/
      FRONTEND_ORIGIN: http://localhost:5173
      AI_API_URL:
      AI_API_KEY:
      BASE_URL: http://localhost:8080
    depends_on:
      - db
      - minio
      - redis
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    ports:
      - "443:443"

volumes:
  db-data:
  minio-data:
