apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
stringData:
  DATABASE_URL: postgres://user:pass@db/production
  JWT_SECRET: changeme
  AWS_ENDPOINT: https://s3.example.com
  AWS_ACCESS_KEY: access_key
  AWS_SECRET_KEY: secret_key
  S3_BUCKET: uploads
  FRONTEND_ORIGIN: https://example.com
  REDIS_URL: redis://redis:6379/
  AI_API_URL: https://ai.example.com
  AI_API_KEY: your-api-key
