apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag | default \"latest\" }}"
            command: ["/usr/local/bin/cleanup"]
            envFrom:
            - secretRef:
                name: backend-env
          restartPolicy: OnFailure
