apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args: ["--config.file=/etc/prometheus/prometheus.yml"]
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: backend
        static_configs:
          - targets: ['backend:9100']
    rule_files:
      - /etc/prometheus/alert-rules.yml
  alert-rules.yml: |
    groups:
      - name: example
        rules:
          - alert: HighLoginFailures
            expr: increase(login_failures_total[5m]) > 5
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: High number of failed logins
          - alert: ManyS3Errors
            expr: increase(s3_errors_total[5m]) > 10
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: S3 errors detected
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
