ALTER TABLE users ADD COLUMN confirmed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN confirmation_token UUID;
ALTER TABLE users ADD COLUMN reset_token UUID;
ALTER TABLE users ADD COLUMN reset_expires_at TIMESTAMP WITH TIME ZONE;
