name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20 # Matches existing setup
      - name: Install Rust toolchain # Explicitly add this for clarity
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install frontend deps
        run: npm install --prefix frontend
      - name: Svelte Check
        run: npm run lint --prefix frontend # Changed from npx svelte-check...
      - name: Run frontend tests
        run: npm test --prefix frontend
      - name: Build frontend
        run: npm run build --prefix frontend # This can also serve as a test that the build passes
      - name: Check backend (Clippy) # Modified Step
        run: cargo clippy --manifest-path backend/Cargo.toml --all-targets -- --deny warnings
      - name: Run backend tests
        run: cargo test --manifest-path backend/Cargo.toml --all-targets
